### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by tsing90** [SunnerLi/RecycleGAN#1]
thanks for sharing this code. I had an issue when running your code, shown as follows:

Traceback (most recent call last):
  File "train.py", line 98, in <module>
    train(args)
  File "train.py", line 94, in train
    eval(args, model, video_a, video_b)
  File "train.py", line 45, in eval
    visualizeSingle(images)
  File "/home/kevin/git/RecycleGAN/lib/utils.py", line 67, in visualizeSingle
    assert (torch.min(image) >= 0) and (torch.max(image) <= 255)
AssertionError

I printed torch.min(image) and torch.max(image), both are 'nan'. It seems that the tensor calculation results into a 'nan' value. 

my environment: 
Ubuntu 16.04
pytorch 0.4.1
python 3.5.6
opencv 3.2

**Comment by SunnerLi** [comment]
Hi @tsing90 ,
I'm sorry that I cannot reply you immediately.
In the theory of RecycleGAN, the loss function is purely composed by `MSE` loss.
Thus the loss function might not the main factor to cause this issue.
Second, you can try to reduce the learning rate,
but I think the problem is neither the gradient explosion.


I also encounter this problem previously, and I get the clue:
At first, we do the normalization before put the data into the model.
However, if the image is **whole black**, the standard deviation might become 0
then the divide-zero problem will occur. 
Because there're some black scene in the white flower domain,
I think it's the main problem to cause `NaN`.


The solution is: you should avoid to use the whole-black image as training data.
You can delete the front 30 frames by yourself.
Since the decode frame are store in the invisible folder,
maybe you should make them visible first:
1. Make the folder visible: `mv .decode decode`
2. Go to the `orange` folder, and try to kill front 30 frames manually.
3. Recover the folder name: `mv decode .decode`


After that, try to train again.
You can get quite successful result :-)
If you have any problem, you can re-open the issue again!

**Comment by tsing90** [comment]
Hi @SunnerLi ,

Many thanks for your detailed answer, very make sense. 

After changing the videos for training AND deleting the original 'result.pkl' file, the problem is solved.
