### ISSUE TITLE
Tested on Windows 10 (1803)

### ISSUE THREAD

**Issue by CoderReece** [SunnerLi/RecycleGAN#3]
This script works fine with my Windows 10 setup. I have CUDA 9.0 and all requirements.
The only thing i had to do to get this working was add ffmpeg to the windows PATH variable.

I recommend anyone else using Windows to use conda to simplify setup.

Thanks, this isn't an issue i just want to alert others that it works on Windows as well as Ubuntu.

**Comment by SunnerLi** [comment]
Hi @tryzombie501 ,
very thanks for your testing!
Since I didn't have any win10 machine with conda, 
I don't guarantee the repository can run on the other OS normally.
However, I'm glad to know the win10 user can also try this repository without changing platform!
I'll close this issue but anyone can find this issue in the close issues part :100:
