### ISSUE TITLE
AssertionError: assert (torch.min(image) >= 0) and (torch.max(image) <= 255)

### ISSUE THREAD

**Issue by takka-919** [SunnerLi/RecycleGAN#4]
Hello, I have below error
```
Traceback (most recent call last):
  File "train.py", line 98, in <module>
    train(args)
  File "train.py", line 94, in train
    eval(args, model, video_a, video_b)
  File "train.py", line 45, in eval
    visualizeSingle(images)
  File "/workspace/RecycleGAN/lib/utils.py", line 67, in visualizeSingle
    assert (torch.min(image) >= 0) and (torch.max(image) <= 255)
AssertionError
```
Do you know what happened?

Thanks.

**Comment by SunnerLi** [comment]
Hi @takka-919 ,
I think we might ensure the training is successful at first.
the assertion is cause since the tensor is not in the valid range.
(for example, the intensity of pixel is nan)
You can check the previous issue #1.
If you have any problem, you can provide more detail information and re-open this issue!
